#pragma once

#using <mscorlib.dll>
#using <System.dll>
#using <System.Xml.dll>
#using <System.Web.Services.dll>
#using <System.EnterpriseServices.dll>

using namespace System::Security::Permissions;
[assembly:SecurityPermissionAttribute(SecurityAction::RequestMinimum, SkipVerification=false)];
// 
// This source code was auto-generated by wsdl, Version=2.0.50727.42.
// 
namespace ControllerSvc {
    using namespace System::Xml::Serialization;
    using namespace System::Web::Services;
    using namespace System::ComponentModel;
    using namespace System::Web::Services::Protocols;
    using namespace System;
    using namespace System::Diagnostics;
    
    using namespace System;
    ref class ControllerClass;
    ref class COpostsyncCompletedEventArgs;
    ref class COsyncCompletedEventArgs;
    ref class COpresyncCompletedEventArgs;
    ref class COinitCompletedEventArgs;
    
    
    /// <remarks/>
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"wsdl", L"2.0.50727.42")]
    public delegate System::Void COpostsyncCompletedEventHandler(System::Object^  sender, ControllerSvc::COpostsyncCompletedEventArgs^  e);
    
    /// <remarks/>
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"wsdl", L"2.0.50727.42")]
    public delegate System::Void COsyncCompletedEventHandler(System::Object^  sender, ControllerSvc::COsyncCompletedEventArgs^  e);
    
    /// <remarks/>
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"wsdl", L"2.0.50727.42")]
    public delegate System::Void COpresyncCompletedEventHandler(System::Object^  sender, ControllerSvc::COpresyncCompletedEventArgs^  e);
    
    /// <remarks/>
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"wsdl", L"2.0.50727.42")]
    public delegate System::Void COinitCompletedEventHandler(System::Object^  sender, ControllerSvc::COinitCompletedEventArgs^  e);
    
    /// <remarks/>
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"wsdl", L"2.0.50727.42"), 
    System::Diagnostics::DebuggerStepThroughAttribute, 
    System::ComponentModel::DesignerCategoryAttribute(L"code"), 
    System::Web::Services::WebServiceBindingAttribute(Name=L"ControllerClassSoap", Namespace=L"www.inf.uth.gr/webservices/somagion_revythas/Controller")]
    public ref class ControllerClass : public System::Web::Services::Protocols::SoapHttpClientProtocol {
        
        private: System::Threading::SendOrPostCallback^  COpostsyncOperationCompleted;
        
        private: System::Threading::SendOrPostCallback^  COsyncOperationCompleted;
        
        private: System::Threading::SendOrPostCallback^  COpresyncOperationCompleted;
        
        private: System::Threading::SendOrPostCallback^  COinitOperationCompleted;
        
        /// <remarks/>
        public: event ControllerSvc::COpostsyncCompletedEventHandler^  COpostsyncCompleted;
        
        /// <remarks/>
        public: event ControllerSvc::COsyncCompletedEventHandler^  COsyncCompleted;
        
        /// <remarks/>
        public: event ControllerSvc::COpresyncCompletedEventHandler^  COpresyncCompleted;
        
        /// <remarks/>
        public: event ControllerSvc::COinitCompletedEventHandler^  COinitCompleted;
        
        /// <remarks/>
        public: ControllerClass();
        /// <remarks/>
        public: [System::Web::Services::Protocols::SoapDocumentMethodAttribute(L"www.inf.uth.gr/webservices/somagion_revythas/Controller/COpostsync", 
            RequestNamespace=L"www.inf.uth.gr/webservices/somagion_revythas/Controller", ResponseNamespace=L"www.inf.uth.gr/webservices/somagion_revythas/Controller", 
            Use=System::Web::Services::Description::SoapBindingUse::Literal, ParameterStyle=System::Web::Services::Protocols::SoapParameterStyle::Wrapped)]
        System::Double COpostsync(System::Int32 control_mode, System::Double base_setpoint);
        
        /// <remarks/>
        public: System::IAsyncResult^  BeginCOpostsync(System::Int32 control_mode, System::Double base_setpoint, System::AsyncCallback^  callback, 
                    System::Object^  asyncState);
        
        /// <remarks/>
        public: System::Double EndCOpostsync(System::IAsyncResult^  asyncResult);
        
        /// <remarks/>
        public: System::Void COpostsyncAsync(System::Int32 control_mode, System::Double base_setpoint);
        
        /// <remarks/>
        public: System::Void COpostsyncAsync(System::Int32 control_mode, System::Double base_setpoint, System::Object^  userState);
        
        private: System::Void OnCOpostsyncOperationCompleted(System::Object^  arg);
        
        /// <remarks/>
        public: [System::Web::Services::Protocols::SoapDocumentMethodAttribute(L"www.inf.uth.gr/webservices/somagion_revythas/Controller/COsync", 
            RequestNamespace=L"www.inf.uth.gr/webservices/somagion_revythas/Controller", ResponseNamespace=L"www.inf.uth.gr/webservices/somagion_revythas/Controller", 
            Use=System::Web::Services::Description::SoapBindingUse::Literal, ParameterStyle=System::Web::Services::Protocols::SoapParameterStyle::Wrapped)]
        System::Double COsync(
                    System::Double load, 
                    System::Double demand, 
                    System::Int32 pstate, 
                    System::Double total, 
                    System::Double target, 
                    System::Double pAvg, 
                    System::Double pStd, 
                    System::Double base_setpoint, 
                    System::Int32 control_mode, 
                    System::Double market_current_frameclearing_price);
        
        /// <remarks/>
        public: System::IAsyncResult^  BeginCOsync(
                    System::Double load, 
                    System::Double demand, 
                    System::Int32 pstate, 
                    System::Double total, 
                    System::Double target, 
                    System::Double pAvg, 
                    System::Double pStd, 
                    System::Double base_setpoint, 
                    System::Int32 control_mode, 
                    System::Double market_current_frameclearing_price, 
                    System::AsyncCallback^  callback, 
                    System::Object^  asyncState);
        
        /// <remarks/>
        public: System::Double EndCOsync(System::IAsyncResult^  asyncResult);
        
        /// <remarks/>
        public: System::Void COsyncAsync(
                    System::Double load, 
                    System::Double demand, 
                    System::Int32 pstate, 
                    System::Double total, 
                    System::Double target, 
                    System::Double pAvg, 
                    System::Double pStd, 
                    System::Double base_setpoint, 
                    System::Int32 control_mode, 
                    System::Double market_current_frameclearing_price);
        
        /// <remarks/>
        public: System::Void COsyncAsync(
                    System::Double load, 
                    System::Double demand, 
                    System::Int32 pstate, 
                    System::Double total, 
                    System::Double target, 
                    System::Double pAvg, 
                    System::Double pStd, 
                    System::Double base_setpoint, 
                    System::Int32 control_mode, 
                    System::Double market_current_frameclearing_price, 
                    System::Object^  userState);
        
        private: System::Void OnCOsyncOperationCompleted(System::Object^  arg);
        
        /// <remarks/>
        public: [System::Web::Services::Protocols::SoapDocumentMethodAttribute(L"www.inf.uth.gr/webservices/somagion_revythas/Controller/COpresync", 
            RequestNamespace=L"www.inf.uth.gr/webservices/somagion_revythas/Controller", ResponseNamespace=L"www.inf.uth.gr/webservices/somagion_revythas/Controller", 
            Use=System::Web::Services::Description::SoapBindingUse::Literal, ParameterStyle=System::Web::Services::Protocols::SoapParameterStyle::Wrapped)]
        System::Int32 COpresync(System::Double base_setpoint, System::Double psetpoint, System::Int32 control_mode);
        
        /// <remarks/>
        public: System::IAsyncResult^  BeginCOpresync(System::Double base_setpoint, System::Double psetpoint, System::Int32 control_mode, 
                    System::AsyncCallback^  callback, System::Object^  asyncState);
        
        /// <remarks/>
        public: System::Int32 EndCOpresync(System::IAsyncResult^  asyncResult);
        
        /// <remarks/>
        public: System::Void COpresyncAsync(System::Double base_setpoint, System::Double psetpoint, System::Int32 control_mode);
        
        /// <remarks/>
        public: System::Void COpresyncAsync(System::Double base_setpoint, System::Double psetpoint, System::Int32 control_mode, 
                    System::Object^  userState);
        
        private: System::Void OnCOpresyncOperationCompleted(System::Object^  arg);
        
        /// <remarks/>
        public: [System::Web::Services::Protocols::SoapDocumentMethodAttribute(L"www.inf.uth.gr/webservices/somagion_revythas/Controller/COinit", 
            RequestNamespace=L"www.inf.uth.gr/webservices/somagion_revythas/Controller", ResponseNamespace=L"www.inf.uth.gr/webservices/somagion_revythas/Controller", 
            Use=System::Web::Services::Description::SoapBindingUse::Literal, ParameterStyle=System::Web::Services::Protocols::SoapParameterStyle::Wrapped)]
        System::Double COinit(
                    System::Double market_init_price, 
                    System::Int32 pstate, 
                    System::Int32 market_period, 
                    System::Int32 control_mode, 
                    System::Double psetpoint, 
                    System::Double base_setpoint, 
                    System::Double heating_base_setpoint, 
                    System::Double cooling_base_setpoint);
        
        /// <remarks/>
        public: System::IAsyncResult^  BeginCOinit(
                    System::Double market_init_price, 
                    System::Int32 pstate, 
                    System::Int32 market_period, 
                    System::Int32 control_mode, 
                    System::Double psetpoint, 
                    System::Double base_setpoint, 
                    System::Double heating_base_setpoint, 
                    System::Double cooling_base_setpoint, 
                    System::AsyncCallback^  callback, 
                    System::Object^  asyncState);
        
        /// <remarks/>
        public: System::Double EndCOinit(System::IAsyncResult^  asyncResult);
        
        /// <remarks/>
        public: System::Void COinitAsync(
                    System::Double market_init_price, 
                    System::Int32 pstate, 
                    System::Int32 market_period, 
                    System::Int32 control_mode, 
                    System::Double psetpoint, 
                    System::Double base_setpoint, 
                    System::Double heating_base_setpoint, 
                    System::Double cooling_base_setpoint);
        
        /// <remarks/>
        public: System::Void COinitAsync(
                    System::Double market_init_price, 
                    System::Int32 pstate, 
                    System::Int32 market_period, 
                    System::Int32 control_mode, 
                    System::Double psetpoint, 
                    System::Double base_setpoint, 
                    System::Double heating_base_setpoint, 
                    System::Double cooling_base_setpoint, 
                    System::Object^  userState);
        
        private: System::Void OnCOinitOperationCompleted(System::Object^  arg);
        
        /// <remarks/>
        public: System::Void CancelAsync(System::Object^  userState) new;
    };
    
    /// <remarks/>
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"wsdl", L"2.0.50727.42"), 
    System::Diagnostics::DebuggerStepThroughAttribute, 
    System::ComponentModel::DesignerCategoryAttribute(L"code")]
    public ref class COpostsyncCompletedEventArgs : public System::ComponentModel::AsyncCompletedEventArgs {
        
        private: cli::array< System::Object^  >^  results;
        
        internal: COpostsyncCompletedEventArgs(cli::array< System::Object^  >^  results, System::Exception^  exception, System::Boolean cancelled, 
                    System::Object^  userState);
        /// <remarks/>
        public: property System::Double Result {
            System::Double get();
        }
    };
    
    /// <remarks/>
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"wsdl", L"2.0.50727.42"), 
    System::Diagnostics::DebuggerStepThroughAttribute, 
    System::ComponentModel::DesignerCategoryAttribute(L"code")]
    public ref class COsyncCompletedEventArgs : public System::ComponentModel::AsyncCompletedEventArgs {
        
        private: cli::array< System::Object^  >^  results;
        
        internal: COsyncCompletedEventArgs(cli::array< System::Object^  >^  results, System::Exception^  exception, System::Boolean cancelled, 
                    System::Object^  userState);
        /// <remarks/>
        public: property System::Double Result {
            System::Double get();
        }
    };
    
    /// <remarks/>
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"wsdl", L"2.0.50727.42"), 
    System::Diagnostics::DebuggerStepThroughAttribute, 
    System::ComponentModel::DesignerCategoryAttribute(L"code")]
    public ref class COpresyncCompletedEventArgs : public System::ComponentModel::AsyncCompletedEventArgs {
        
        private: cli::array< System::Object^  >^  results;
        
        internal: COpresyncCompletedEventArgs(cli::array< System::Object^  >^  results, System::Exception^  exception, System::Boolean cancelled, 
                    System::Object^  userState);
        /// <remarks/>
        public: property System::Int32 Result {
            System::Int32 get();
        }
    };
    
    /// <remarks/>
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"wsdl", L"2.0.50727.42"), 
    System::Diagnostics::DebuggerStepThroughAttribute, 
    System::ComponentModel::DesignerCategoryAttribute(L"code")]
    public ref class COinitCompletedEventArgs : public System::ComponentModel::AsyncCompletedEventArgs {
        
        private: cli::array< System::Object^  >^  results;
        
        internal: COinitCompletedEventArgs(cli::array< System::Object^  >^  results, System::Exception^  exception, System::Boolean cancelled, 
                    System::Object^  userState);
        /// <remarks/>
        public: property System::Double Result {
            System::Double get();
        }
    };
}
namespace ControllerSvc {
    
    
    inline ControllerClass::ControllerClass() {
        this->Url = L"http://10.96.12.51/ControllerSetup/Controller.asmx";
    }
    
    inline System::Double ControllerClass::COpostsync(System::Int32 control_mode, System::Double base_setpoint) {
        cli::array< System::Object^  >^  results = this->Invoke(L"COpostsync", gcnew cli::array< System::Object^  >(2) {control_mode, 
                base_setpoint});
        return (*cli::safe_cast<System::Double^>(results[0]));
    }
    
    inline System::IAsyncResult^  ControllerClass::BeginCOpostsync(System::Int32 control_mode, System::Double base_setpoint, 
                System::AsyncCallback^  callback, System::Object^  asyncState) {
        return this->BeginInvoke(L"COpostsync", gcnew cli::array< System::Object^  >(2) {control_mode, base_setpoint}, callback, 
            asyncState);
    }
    
    inline System::Double ControllerClass::EndCOpostsync(System::IAsyncResult^  asyncResult) {
        cli::array< System::Object^  >^  results = this->EndInvoke(asyncResult);
        return (*cli::safe_cast<System::Double^>(results[0]));
    }
    
    inline System::Void ControllerClass::COpostsyncAsync(System::Int32 control_mode, System::Double base_setpoint) {
        this->COpostsyncAsync(control_mode, base_setpoint, nullptr);
    }
    
    inline System::Void ControllerClass::COpostsyncAsync(System::Int32 control_mode, System::Double base_setpoint, System::Object^  userState) {
        if (this->COpostsyncOperationCompleted == nullptr) {
            this->COpostsyncOperationCompleted = gcnew System::Threading::SendOrPostCallback(this, &ControllerSvc::ControllerClass::OnCOpostsyncOperationCompleted);
        }
        this->InvokeAsync(L"COpostsync", gcnew cli::array< System::Object^  >(2) {control_mode, base_setpoint}, this->COpostsyncOperationCompleted, 
            userState);
    }
    
    inline System::Void ControllerClass::OnCOpostsyncOperationCompleted(System::Object^  arg) {
        {
            System::Web::Services::Protocols::InvokeCompletedEventArgs^  invokeArgs = (cli::safe_cast<System::Web::Services::Protocols::InvokeCompletedEventArgs^  >(arg));
            this->COpostsyncCompleted(this, (gcnew ControllerSvc::COpostsyncCompletedEventArgs(invokeArgs->Results, invokeArgs->Error, 
                    invokeArgs->Cancelled, invokeArgs->UserState)));
        }
    }
    
    inline System::Double ControllerClass::COsync(
                System::Double load, 
                System::Double demand, 
                System::Int32 pstate, 
                System::Double total, 
                System::Double target, 
                System::Double pAvg, 
                System::Double pStd, 
                System::Double base_setpoint, 
                System::Int32 control_mode, 
                System::Double market_current_frameclearing_price) {
        cli::array< System::Object^  >^  results = this->Invoke(L"COsync", gcnew cli::array< System::Object^  >(10) {load, 
                demand, pstate, total, target, pAvg, pStd, base_setpoint, control_mode, market_current_frameclearing_price});
        return (*cli::safe_cast<System::Double^>(results[0]));
    }
    
    inline System::IAsyncResult^  ControllerClass::BeginCOsync(
                System::Double load, 
                System::Double demand, 
                System::Int32 pstate, 
                System::Double total, 
                System::Double target, 
                System::Double pAvg, 
                System::Double pStd, 
                System::Double base_setpoint, 
                System::Int32 control_mode, 
                System::Double market_current_frameclearing_price, 
                System::AsyncCallback^  callback, 
                System::Object^  asyncState) {
        return this->BeginInvoke(L"COsync", gcnew cli::array< System::Object^  >(10) {load, demand, pstate, total, target, 
                pAvg, pStd, base_setpoint, control_mode, market_current_frameclearing_price}, callback, asyncState);
    }
    
    inline System::Double ControllerClass::EndCOsync(System::IAsyncResult^  asyncResult) {
        cli::array< System::Object^  >^  results = this->EndInvoke(asyncResult);
        return (*cli::safe_cast<System::Double^>(results[0]));
    }
    
    inline System::Void ControllerClass::COsyncAsync(
                System::Double load, 
                System::Double demand, 
                System::Int32 pstate, 
                System::Double total, 
                System::Double target, 
                System::Double pAvg, 
                System::Double pStd, 
                System::Double base_setpoint, 
                System::Int32 control_mode, 
                System::Double market_current_frameclearing_price) {
        this->COsyncAsync(load, demand, pstate, total, target, pAvg, pStd, base_setpoint, control_mode, market_current_frameclearing_price, 
            nullptr);
    }
    
    inline System::Void ControllerClass::COsyncAsync(
                System::Double load, 
                System::Double demand, 
                System::Int32 pstate, 
                System::Double total, 
                System::Double target, 
                System::Double pAvg, 
                System::Double pStd, 
                System::Double base_setpoint, 
                System::Int32 control_mode, 
                System::Double market_current_frameclearing_price, 
                System::Object^  userState) {
        if (this->COsyncOperationCompleted == nullptr) {
            this->COsyncOperationCompleted = gcnew System::Threading::SendOrPostCallback(this, &ControllerSvc::ControllerClass::OnCOsyncOperationCompleted);
        }
        this->InvokeAsync(L"COsync", gcnew cli::array< System::Object^  >(10) {load, demand, pstate, total, target, pAvg, 
                pStd, base_setpoint, control_mode, market_current_frameclearing_price}, this->COsyncOperationCompleted, userState);
    }
    
    inline System::Void ControllerClass::OnCOsyncOperationCompleted(System::Object^  arg) {
        {
            System::Web::Services::Protocols::InvokeCompletedEventArgs^  invokeArgs = (cli::safe_cast<System::Web::Services::Protocols::InvokeCompletedEventArgs^  >(arg));
            this->COsyncCompleted(this, (gcnew ControllerSvc::COsyncCompletedEventArgs(invokeArgs->Results, invokeArgs->Error, 
                    invokeArgs->Cancelled, invokeArgs->UserState)));
        }
    }
    
    inline System::Int32 ControllerClass::COpresync(System::Double base_setpoint, System::Double psetpoint, System::Int32 control_mode) {
        cli::array< System::Object^  >^  results = this->Invoke(L"COpresync", gcnew cli::array< System::Object^  >(3) {base_setpoint, 
                psetpoint, control_mode});
        return (*cli::safe_cast<System::Int32^>(results[0]));
    }
    
    inline System::IAsyncResult^  ControllerClass::BeginCOpresync(System::Double base_setpoint, System::Double psetpoint, 
                System::Int32 control_mode, System::AsyncCallback^  callback, System::Object^  asyncState) {
        return this->BeginInvoke(L"COpresync", gcnew cli::array< System::Object^  >(3) {base_setpoint, psetpoint, control_mode}, 
            callback, asyncState);
    }
    
    inline System::Int32 ControllerClass::EndCOpresync(System::IAsyncResult^  asyncResult) {
        cli::array< System::Object^  >^  results = this->EndInvoke(asyncResult);
        return (*cli::safe_cast<System::Int32^>(results[0]));
    }
    
    inline System::Void ControllerClass::COpresyncAsync(System::Double base_setpoint, System::Double psetpoint, System::Int32 control_mode) {
        this->COpresyncAsync(base_setpoint, psetpoint, control_mode, nullptr);
    }
    
    inline System::Void ControllerClass::COpresyncAsync(System::Double base_setpoint, System::Double psetpoint, System::Int32 control_mode, 
                System::Object^  userState) {
        if (this->COpresyncOperationCompleted == nullptr) {
            this->COpresyncOperationCompleted = gcnew System::Threading::SendOrPostCallback(this, &ControllerSvc::ControllerClass::OnCOpresyncOperationCompleted);
        }
        this->InvokeAsync(L"COpresync", gcnew cli::array< System::Object^  >(3) {base_setpoint, psetpoint, control_mode}, this->COpresyncOperationCompleted, 
            userState);
    }
    
    inline System::Void ControllerClass::OnCOpresyncOperationCompleted(System::Object^  arg) {
        {
            System::Web::Services::Protocols::InvokeCompletedEventArgs^  invokeArgs = (cli::safe_cast<System::Web::Services::Protocols::InvokeCompletedEventArgs^  >(arg));
            this->COpresyncCompleted(this, (gcnew ControllerSvc::COpresyncCompletedEventArgs(invokeArgs->Results, invokeArgs->Error, 
                    invokeArgs->Cancelled, invokeArgs->UserState)));
        }
    }
    
    inline System::Double ControllerClass::COinit(
                System::Double market_init_price, 
                System::Int32 pstate, 
                System::Int32 market_period, 
                System::Int32 control_mode, 
                System::Double psetpoint, 
                System::Double base_setpoint, 
                System::Double heating_base_setpoint, 
                System::Double cooling_base_setpoint) {
        cli::array< System::Object^  >^  results = this->Invoke(L"COinit", gcnew cli::array< System::Object^  >(8) {market_init_price, 
                pstate, market_period, control_mode, psetpoint, base_setpoint, heating_base_setpoint, cooling_base_setpoint});
        return (*cli::safe_cast<System::Double^>(results[0]));
    }
    
    inline System::IAsyncResult^  ControllerClass::BeginCOinit(
                System::Double market_init_price, 
                System::Int32 pstate, 
                System::Int32 market_period, 
                System::Int32 control_mode, 
                System::Double psetpoint, 
                System::Double base_setpoint, 
                System::Double heating_base_setpoint, 
                System::Double cooling_base_setpoint, 
                System::AsyncCallback^  callback, 
                System::Object^  asyncState) {
        return this->BeginInvoke(L"COinit", gcnew cli::array< System::Object^  >(8) {market_init_price, pstate, market_period, 
                control_mode, psetpoint, base_setpoint, heating_base_setpoint, cooling_base_setpoint}, callback, asyncState);
    }
    
    inline System::Double ControllerClass::EndCOinit(System::IAsyncResult^  asyncResult) {
        cli::array< System::Object^  >^  results = this->EndInvoke(asyncResult);
        return (*cli::safe_cast<System::Double^>(results[0]));
    }
    
    inline System::Void ControllerClass::COinitAsync(
                System::Double market_init_price, 
                System::Int32 pstate, 
                System::Int32 market_period, 
                System::Int32 control_mode, 
                System::Double psetpoint, 
                System::Double base_setpoint, 
                System::Double heating_base_setpoint, 
                System::Double cooling_base_setpoint) {
        this->COinitAsync(market_init_price, pstate, market_period, control_mode, psetpoint, base_setpoint, heating_base_setpoint, 
            cooling_base_setpoint, nullptr);
    }
    
    inline System::Void ControllerClass::COinitAsync(
                System::Double market_init_price, 
                System::Int32 pstate, 
                System::Int32 market_period, 
                System::Int32 control_mode, 
                System::Double psetpoint, 
                System::Double base_setpoint, 
                System::Double heating_base_setpoint, 
                System::Double cooling_base_setpoint, 
                System::Object^  userState) {
        if (this->COinitOperationCompleted == nullptr) {
            this->COinitOperationCompleted = gcnew System::Threading::SendOrPostCallback(this, &ControllerSvc::ControllerClass::OnCOinitOperationCompleted);
        }
        this->InvokeAsync(L"COinit", gcnew cli::array< System::Object^  >(8) {market_init_price, pstate, market_period, control_mode, 
                psetpoint, base_setpoint, heating_base_setpoint, cooling_base_setpoint}, this->COinitOperationCompleted, userState);
    }
    
    inline System::Void ControllerClass::OnCOinitOperationCompleted(System::Object^  arg) {
        {
            System::Web::Services::Protocols::InvokeCompletedEventArgs^  invokeArgs = (cli::safe_cast<System::Web::Services::Protocols::InvokeCompletedEventArgs^  >(arg));
            this->COinitCompleted(this, (gcnew ControllerSvc::COinitCompletedEventArgs(invokeArgs->Results, invokeArgs->Error, 
                    invokeArgs->Cancelled, invokeArgs->UserState)));
        }
    }
    
    inline System::Void ControllerClass::CancelAsync(System::Object^  userState) {
        __super::CancelAsync(userState);
    }
    
    
    inline COpostsyncCompletedEventArgs::COpostsyncCompletedEventArgs(cli::array< System::Object^  >^  results, System::Exception^  exception, 
                System::Boolean cancelled, System::Object^  userState) : 
            System::ComponentModel::AsyncCompletedEventArgs(exception, cancelled, userState) {
        this->results = results;
    }
    
    inline System::Double COpostsyncCompletedEventArgs::Result::get() {
        this->RaiseExceptionIfNecessary();
        return (*cli::safe_cast<System::Double^>(this->results[0]));
    }
    
    
    inline COsyncCompletedEventArgs::COsyncCompletedEventArgs(cli::array< System::Object^  >^  results, System::Exception^  exception, 
                System::Boolean cancelled, System::Object^  userState) : 
            System::ComponentModel::AsyncCompletedEventArgs(exception, cancelled, userState) {
        this->results = results;
    }
    
    inline System::Double COsyncCompletedEventArgs::Result::get() {
        this->RaiseExceptionIfNecessary();
        return (*cli::safe_cast<System::Double^>(this->results[0]));
    }
    
    
    inline COpresyncCompletedEventArgs::COpresyncCompletedEventArgs(cli::array< System::Object^  >^  results, System::Exception^  exception, 
                System::Boolean cancelled, System::Object^  userState) : 
            System::ComponentModel::AsyncCompletedEventArgs(exception, cancelled, userState) {
        this->results = results;
    }
    
    inline System::Int32 COpresyncCompletedEventArgs::Result::get() {
        this->RaiseExceptionIfNecessary();
        return (*cli::safe_cast<System::Int32^>(this->results[0]));
    }
    
    
    inline COinitCompletedEventArgs::COinitCompletedEventArgs(cli::array< System::Object^  >^  results, System::Exception^  exception, 
                System::Boolean cancelled, System::Object^  userState) : 
            System::ComponentModel::AsyncCompletedEventArgs(exception, cancelled, userState) {
        this->results = results;
    }
    
    inline System::Double COinitCompletedEventArgs::Result::get() {
        this->RaiseExceptionIfNecessary();
        return (*cli::safe_cast<System::Double^>(this->results[0]));
    }
}
