#pragma once

#using <mscorlib.dll>
#using <System.dll>
#using <System.Xml.dll>
#using <System.Web.Services.dll>
#using <System.EnterpriseServices.dll>

using namespace System::Security::Permissions;
[assembly:SecurityPermissionAttribute(SecurityAction::RequestMinimum, SkipVerification=false)];
// 
// This source code was auto-generated by wsdl, Version=2.0.50727.42.
// 
namespace Wind_TurbineSvc {
    using namespace System::Xml::Serialization;
    using namespace System::Web::Services;
    using namespace System::ComponentModel;
    using namespace System::Web::Services::Protocols;
    using namespace System;
    using namespace System::Diagnostics;
    
    using namespace System;
    ref class Wind_turbineClass;
    ref class windturb_dgcreateCompletedEventArgs;
    ref class windturb_dginitCompletedEventArgs;
    ref class windturb_dgsyncCompletedEventArgs;
    ref class windturb_dg_postsyncCompletedEventArgs;
    
    
    /// <remarks/>
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"wsdl", L"2.0.50727.42")]
    public delegate System::Void windturb_dgcreateCompletedEventHandler(System::Object^  sender, Wind_TurbineSvc::windturb_dgcreateCompletedEventArgs^  e);
    
    /// <remarks/>
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"wsdl", L"2.0.50727.42")]
    public delegate System::Void windturb_dginitCompletedEventHandler(System::Object^  sender, Wind_TurbineSvc::windturb_dginitCompletedEventArgs^  e);
    
    /// <remarks/>
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"wsdl", L"2.0.50727.42")]
    public delegate System::Void windturb_dgsyncCompletedEventHandler(System::Object^  sender, Wind_TurbineSvc::windturb_dgsyncCompletedEventArgs^  e);
    
    /// <remarks/>
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"wsdl", L"2.0.50727.42")]
    public delegate System::Void windturb_dg_postsyncCompletedEventHandler(System::Object^  sender, Wind_TurbineSvc::windturb_dg_postsyncCompletedEventArgs^  e);
    
    /// <remarks/>
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"wsdl", L"2.0.50727.42"), 
    System::Diagnostics::DebuggerStepThroughAttribute, 
    System::ComponentModel::DesignerCategoryAttribute(L"code"), 
    System::Web::Services::WebServiceBindingAttribute(Name=L"Wind_turbineClassSoap", Namespace=L"www.inf.uth.gr/webservices/somagion_revythas/WindTurbine")]
    public ref class Wind_turbineClass : public System::Web::Services::Protocols::SoapHttpClientProtocol {
        
        private: System::Threading::SendOrPostCallback^  windturb_dgcreateOperationCompleted;
        
        private: System::Threading::SendOrPostCallback^  windturb_dginitOperationCompleted;
        
        private: System::Threading::SendOrPostCallback^  windturb_dgsyncOperationCompleted;
        
        private: System::Threading::SendOrPostCallback^  windturb_dg_postsyncOperationCompleted;
        
        /// <remarks/>
        public: event Wind_TurbineSvc::windturb_dgcreateCompletedEventHandler^  windturb_dgcreateCompleted;
        
        /// <remarks/>
        public: event Wind_TurbineSvc::windturb_dginitCompletedEventHandler^  windturb_dginitCompleted;
        
        /// <remarks/>
        public: event Wind_TurbineSvc::windturb_dgsyncCompletedEventHandler^  windturb_dgsyncCompleted;
        
        /// <remarks/>
        public: event Wind_TurbineSvc::windturb_dg_postsyncCompletedEventHandler^  windturb_dg_postsyncCompleted;
        
        /// <remarks/>
        public: Wind_turbineClass();
        /// <remarks/>
        public: [System::Web::Services::Protocols::SoapDocumentMethodAttribute(L"www.inf.uth.gr/webservices/somagion_revythas/WindTurbine/windturb_dgcreate", 
            RequestNamespace=L"www.inf.uth.gr/webservices/somagion_revythas/WindTurbine", ResponseNamespace=L"www.inf.uth.gr/webservices/somagion_revythas/WindTurbine", 
            Use=System::Web::Services::Description::SoapBindingUse::Literal, ParameterStyle=System::Web::Services::Protocols::SoapParameterStyle::Wrapped)]
        System::Double windturb_dgcreate();
        
        /// <remarks/>
        public: System::IAsyncResult^  Beginwindturb_dgcreate(System::AsyncCallback^  callback, System::Object^  asyncState);
        
        /// <remarks/>
        public: System::Double Endwindturb_dgcreate(System::IAsyncResult^  asyncResult);
        
        /// <remarks/>
        public: System::Void windturb_dgcreateAsync();
        
        /// <remarks/>
        public: System::Void windturb_dgcreateAsync(System::Object^  userState);
        
        private: System::Void Onwindturb_dgcreateOperationCompleted(System::Object^  arg);
        
        /// <remarks/>
        public: [System::Web::Services::Protocols::SoapDocumentMethodAttribute(L"www.inf.uth.gr/webservices/somagion_revythas/WindTurbine/windturb_dginit", 
            RequestNamespace=L"www.inf.uth.gr/webservices/somagion_revythas/WindTurbine", ResponseNamespace=L"www.inf.uth.gr/webservices/somagion_revythas/WindTurbine", 
            Use=System::Web::Services::Description::SoapBindingUse::Literal, ParameterStyle=System::Web::Services::Protocols::SoapParameterStyle::Wrapped)]
        System::Int32 windturb_dginit(
                    System::Double pLine_I_A_real, 
                    System::Double pLine_I_A_imag, 
                    System::Double pLine_I_B_real, 
                    System::Double pLine_I_B_imag, 
                    System::Double pLine_I_C_real, 
                    System::Double pLine_I_C_imag);
        
        /// <remarks/>
        public: System::IAsyncResult^  Beginwindturb_dginit(
                    System::Double pLine_I_A_real, 
                    System::Double pLine_I_A_imag, 
                    System::Double pLine_I_B_real, 
                    System::Double pLine_I_B_imag, 
                    System::Double pLine_I_C_real, 
                    System::Double pLine_I_C_imag, 
                    System::AsyncCallback^  callback, 
                    System::Object^  asyncState);
        
        /// <remarks/>
        public: System::Int32 Endwindturb_dginit(System::IAsyncResult^  asyncResult);
        
        /// <remarks/>
        public: System::Void windturb_dginitAsync(
                    System::Double pLine_I_A_real, 
                    System::Double pLine_I_A_imag, 
                    System::Double pLine_I_B_real, 
                    System::Double pLine_I_B_imag, 
                    System::Double pLine_I_C_real, 
                    System::Double pLine_I_C_imag);
        
        /// <remarks/>
        public: System::Void windturb_dginitAsync(
                    System::Double pLine_I_A_real, 
                    System::Double pLine_I_A_imag, 
                    System::Double pLine_I_B_real, 
                    System::Double pLine_I_B_imag, 
                    System::Double pLine_I_C_real, 
                    System::Double pLine_I_C_imag, 
                    System::Object^  userState);
        
        private: System::Void Onwindturb_dginitOperationCompleted(System::Object^  arg);
        
        /// <remarks/>
        public: [System::Web::Services::Protocols::SoapDocumentMethodAttribute(L"www.inf.uth.gr/webservices/somagion_revythas/WindTurbine/windturb_dgsync", 
            RequestNamespace=L"www.inf.uth.gr/webservices/somagion_revythas/WindTurbine", ResponseNamespace=L"www.inf.uth.gr/webservices/somagion_revythas/WindTurbine", 
            Use=System::Web::Services::Description::SoapBindingUse::Literal, ParameterStyle=System::Web::Services::Protocols::SoapParameterStyle::Wrapped)]
        System::Double windturb_dgsync(
                    System::Double pCircuit_V_A_real, 
                    System::Double pCircuit_V_A_imag, 
                    System::Double pCircuit_V_B_real, 
                    System::Double pCircuit_V_B_imag, 
                    System::Double pCircuit_V_C_real, 
                    System::Double pCircuit_V_C_imag);
        
        /// <remarks/>
        public: System::IAsyncResult^  Beginwindturb_dgsync(
                    System::Double pCircuit_V_A_real, 
                    System::Double pCircuit_V_A_imag, 
                    System::Double pCircuit_V_B_real, 
                    System::Double pCircuit_V_B_imag, 
                    System::Double pCircuit_V_C_real, 
                    System::Double pCircuit_V_C_imag, 
                    System::AsyncCallback^  callback, 
                    System::Object^  asyncState);
        
        /// <remarks/>
        public: System::Double Endwindturb_dgsync(System::IAsyncResult^  asyncResult);
        
        /// <remarks/>
        public: System::Void windturb_dgsyncAsync(
                    System::Double pCircuit_V_A_real, 
                    System::Double pCircuit_V_A_imag, 
                    System::Double pCircuit_V_B_real, 
                    System::Double pCircuit_V_B_imag, 
                    System::Double pCircuit_V_C_real, 
                    System::Double pCircuit_V_C_imag);
        
        /// <remarks/>
        public: System::Void windturb_dgsyncAsync(
                    System::Double pCircuit_V_A_real, 
                    System::Double pCircuit_V_A_imag, 
                    System::Double pCircuit_V_B_real, 
                    System::Double pCircuit_V_B_imag, 
                    System::Double pCircuit_V_C_real, 
                    System::Double pCircuit_V_C_imag, 
                    System::Object^  userState);
        
        private: System::Void Onwindturb_dgsyncOperationCompleted(System::Object^  arg);
        
        /// <remarks/>
        public: [System::Web::Services::Protocols::SoapDocumentMethodAttribute(L"www.inf.uth.gr/webservices/somagion_revythas/WindTurbine/windturb_dg_postsync", 
            RequestNamespace=L"www.inf.uth.gr/webservices/somagion_revythas/WindTurbine", ResponseNamespace=L"www.inf.uth.gr/webservices/somagion_revythas/WindTurbine", 
            Use=System::Web::Services::Description::SoapBindingUse::Literal, ParameterStyle=System::Web::Services::Protocols::SoapParameterStyle::Wrapped)]
        System::Int32 windturb_dg_postsync(System::Int32 t0, System::Int32 t1);
        
        /// <remarks/>
        public: System::IAsyncResult^  Beginwindturb_dg_postsync(System::Int32 t0, System::Int32 t1, System::AsyncCallback^  callback, 
                    System::Object^  asyncState);
        
        /// <remarks/>
        public: System::Int32 Endwindturb_dg_postsync(System::IAsyncResult^  asyncResult);
        
        /// <remarks/>
        public: System::Void windturb_dg_postsyncAsync(System::Int32 t0, System::Int32 t1);
        
        /// <remarks/>
        public: System::Void windturb_dg_postsyncAsync(System::Int32 t0, System::Int32 t1, System::Object^  userState);
        
        private: System::Void Onwindturb_dg_postsyncOperationCompleted(System::Object^  arg);
        
        /// <remarks/>
        public: System::Void CancelAsync(System::Object^  userState) new;
    };
    
    /// <remarks/>
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"wsdl", L"2.0.50727.42"), 
    System::Diagnostics::DebuggerStepThroughAttribute, 
    System::ComponentModel::DesignerCategoryAttribute(L"code")]
    public ref class windturb_dgcreateCompletedEventArgs : public System::ComponentModel::AsyncCompletedEventArgs {
        
        private: cli::array< System::Object^  >^  results;
        
        internal: windturb_dgcreateCompletedEventArgs(cli::array< System::Object^  >^  results, System::Exception^  exception, 
                    System::Boolean cancelled, System::Object^  userState);
        /// <remarks/>
        public: property System::Double Result {
            System::Double get();
        }
    };
    
    /// <remarks/>
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"wsdl", L"2.0.50727.42"), 
    System::Diagnostics::DebuggerStepThroughAttribute, 
    System::ComponentModel::DesignerCategoryAttribute(L"code")]
    public ref class windturb_dginitCompletedEventArgs : public System::ComponentModel::AsyncCompletedEventArgs {
        
        private: cli::array< System::Object^  >^  results;
        
        internal: windturb_dginitCompletedEventArgs(cli::array< System::Object^  >^  results, System::Exception^  exception, 
                    System::Boolean cancelled, System::Object^  userState);
        /// <remarks/>
        public: property System::Int32 Result {
            System::Int32 get();
        }
    };
    
    /// <remarks/>
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"wsdl", L"2.0.50727.42"), 
    System::Diagnostics::DebuggerStepThroughAttribute, 
    System::ComponentModel::DesignerCategoryAttribute(L"code")]
    public ref class windturb_dgsyncCompletedEventArgs : public System::ComponentModel::AsyncCompletedEventArgs {
        
        private: cli::array< System::Object^  >^  results;
        
        internal: windturb_dgsyncCompletedEventArgs(cli::array< System::Object^  >^  results, System::Exception^  exception, 
                    System::Boolean cancelled, System::Object^  userState);
        /// <remarks/>
        public: property System::Double Result {
            System::Double get();
        }
    };
    
    /// <remarks/>
    [System::CodeDom::Compiler::GeneratedCodeAttribute(L"wsdl", L"2.0.50727.42"), 
    System::Diagnostics::DebuggerStepThroughAttribute, 
    System::ComponentModel::DesignerCategoryAttribute(L"code")]
    public ref class windturb_dg_postsyncCompletedEventArgs : public System::ComponentModel::AsyncCompletedEventArgs {
        
        private: cli::array< System::Object^  >^  results;
        
        internal: windturb_dg_postsyncCompletedEventArgs(cli::array< System::Object^  >^  results, System::Exception^  exception, 
                    System::Boolean cancelled, System::Object^  userState);
        /// <remarks/>
        public: property System::Int32 Result {
            System::Int32 get();
        }
    };
}
namespace Wind_TurbineSvc {
    
    
    inline Wind_turbineClass::Wind_turbineClass() {
        this->Url = L"http://10.96.12.51/Wind_turbine_setup/Wind_turbine.asmx";
    }
    
    inline System::Double Wind_turbineClass::windturb_dgcreate() {
        cli::array< System::Object^  >^  results = this->Invoke(L"windturb_dgcreate", gcnew cli::array< System::Object^  >(0));
        return (*cli::safe_cast<System::Double^>(results[0]));
    }
    
    inline System::IAsyncResult^  Wind_turbineClass::Beginwindturb_dgcreate(System::AsyncCallback^  callback, System::Object^  asyncState) {
        return this->BeginInvoke(L"windturb_dgcreate", gcnew cli::array< System::Object^  >(0), callback, asyncState);
    }
    
    inline System::Double Wind_turbineClass::Endwindturb_dgcreate(System::IAsyncResult^  asyncResult) {
        cli::array< System::Object^  >^  results = this->EndInvoke(asyncResult);
        return (*cli::safe_cast<System::Double^>(results[0]));
    }
    
    inline System::Void Wind_turbineClass::windturb_dgcreateAsync() {
        this->windturb_dgcreateAsync(nullptr);
    }
    
    inline System::Void Wind_turbineClass::windturb_dgcreateAsync(System::Object^  userState) {
        if (this->windturb_dgcreateOperationCompleted == nullptr) {
            this->windturb_dgcreateOperationCompleted = gcnew System::Threading::SendOrPostCallback(this, &Wind_TurbineSvc::Wind_turbineClass::Onwindturb_dgcreateOperationCompleted);
        }
        this->InvokeAsync(L"windturb_dgcreate", gcnew cli::array< System::Object^  >(0), this->windturb_dgcreateOperationCompleted, 
            userState);
    }
    
    inline System::Void Wind_turbineClass::Onwindturb_dgcreateOperationCompleted(System::Object^  arg) {
        {
            System::Web::Services::Protocols::InvokeCompletedEventArgs^  invokeArgs = (cli::safe_cast<System::Web::Services::Protocols::InvokeCompletedEventArgs^  >(arg));
            this->windturb_dgcreateCompleted(this, (gcnew Wind_TurbineSvc::windturb_dgcreateCompletedEventArgs(invokeArgs->Results, 
                    invokeArgs->Error, invokeArgs->Cancelled, invokeArgs->UserState)));
        }
    }
    
    inline System::Int32 Wind_turbineClass::windturb_dginit(
                System::Double pLine_I_A_real, 
                System::Double pLine_I_A_imag, 
                System::Double pLine_I_B_real, 
                System::Double pLine_I_B_imag, 
                System::Double pLine_I_C_real, 
                System::Double pLine_I_C_imag) {
        cli::array< System::Object^  >^  results = this->Invoke(L"windturb_dginit", gcnew cli::array< System::Object^  >(6) {pLine_I_A_real, 
                pLine_I_A_imag, pLine_I_B_real, pLine_I_B_imag, pLine_I_C_real, pLine_I_C_imag});
        return (*cli::safe_cast<System::Int32^>(results[0]));
    }
    
    inline System::IAsyncResult^  Wind_turbineClass::Beginwindturb_dginit(
                System::Double pLine_I_A_real, 
                System::Double pLine_I_A_imag, 
                System::Double pLine_I_B_real, 
                System::Double pLine_I_B_imag, 
                System::Double pLine_I_C_real, 
                System::Double pLine_I_C_imag, 
                System::AsyncCallback^  callback, 
                System::Object^  asyncState) {
        return this->BeginInvoke(L"windturb_dginit", gcnew cli::array< System::Object^  >(6) {pLine_I_A_real, pLine_I_A_imag, 
                pLine_I_B_real, pLine_I_B_imag, pLine_I_C_real, pLine_I_C_imag}, callback, asyncState);
    }
    
    inline System::Int32 Wind_turbineClass::Endwindturb_dginit(System::IAsyncResult^  asyncResult) {
        cli::array< System::Object^  >^  results = this->EndInvoke(asyncResult);
        return (*cli::safe_cast<System::Int32^>(results[0]));
    }
    
    inline System::Void Wind_turbineClass::windturb_dginitAsync(
                System::Double pLine_I_A_real, 
                System::Double pLine_I_A_imag, 
                System::Double pLine_I_B_real, 
                System::Double pLine_I_B_imag, 
                System::Double pLine_I_C_real, 
                System::Double pLine_I_C_imag) {
        this->windturb_dginitAsync(pLine_I_A_real, pLine_I_A_imag, pLine_I_B_real, pLine_I_B_imag, pLine_I_C_real, pLine_I_C_imag, 
            nullptr);
    }
    
    inline System::Void Wind_turbineClass::windturb_dginitAsync(
                System::Double pLine_I_A_real, 
                System::Double pLine_I_A_imag, 
                System::Double pLine_I_B_real, 
                System::Double pLine_I_B_imag, 
                System::Double pLine_I_C_real, 
                System::Double pLine_I_C_imag, 
                System::Object^  userState) {
        if (this->windturb_dginitOperationCompleted == nullptr) {
            this->windturb_dginitOperationCompleted = gcnew System::Threading::SendOrPostCallback(this, &Wind_TurbineSvc::Wind_turbineClass::Onwindturb_dginitOperationCompleted);
        }
        this->InvokeAsync(L"windturb_dginit", gcnew cli::array< System::Object^  >(6) {pLine_I_A_real, pLine_I_A_imag, pLine_I_B_real, 
                pLine_I_B_imag, pLine_I_C_real, pLine_I_C_imag}, this->windturb_dginitOperationCompleted, userState);
    }
    
    inline System::Void Wind_turbineClass::Onwindturb_dginitOperationCompleted(System::Object^  arg) {
        {
            System::Web::Services::Protocols::InvokeCompletedEventArgs^  invokeArgs = (cli::safe_cast<System::Web::Services::Protocols::InvokeCompletedEventArgs^  >(arg));
            this->windturb_dginitCompleted(this, (gcnew Wind_TurbineSvc::windturb_dginitCompletedEventArgs(invokeArgs->Results, 
                    invokeArgs->Error, invokeArgs->Cancelled, invokeArgs->UserState)));
        }
    }
    
    inline System::Double Wind_turbineClass::windturb_dgsync(
                System::Double pCircuit_V_A_real, 
                System::Double pCircuit_V_A_imag, 
                System::Double pCircuit_V_B_real, 
                System::Double pCircuit_V_B_imag, 
                System::Double pCircuit_V_C_real, 
                System::Double pCircuit_V_C_imag) {
        cli::array< System::Object^  >^  results = this->Invoke(L"windturb_dgsync", gcnew cli::array< System::Object^  >(6) {pCircuit_V_A_real, 
                pCircuit_V_A_imag, pCircuit_V_B_real, pCircuit_V_B_imag, pCircuit_V_C_real, pCircuit_V_C_imag});
        return (*cli::safe_cast<System::Double^>(results[0]));
    }
    
    inline System::IAsyncResult^  Wind_turbineClass::Beginwindturb_dgsync(
                System::Double pCircuit_V_A_real, 
                System::Double pCircuit_V_A_imag, 
                System::Double pCircuit_V_B_real, 
                System::Double pCircuit_V_B_imag, 
                System::Double pCircuit_V_C_real, 
                System::Double pCircuit_V_C_imag, 
                System::AsyncCallback^  callback, 
                System::Object^  asyncState) {
        return this->BeginInvoke(L"windturb_dgsync", gcnew cli::array< System::Object^  >(6) {pCircuit_V_A_real, pCircuit_V_A_imag, 
                pCircuit_V_B_real, pCircuit_V_B_imag, pCircuit_V_C_real, pCircuit_V_C_imag}, callback, asyncState);
    }
    
    inline System::Double Wind_turbineClass::Endwindturb_dgsync(System::IAsyncResult^  asyncResult) {
        cli::array< System::Object^  >^  results = this->EndInvoke(asyncResult);
        return (*cli::safe_cast<System::Double^>(results[0]));
    }
    
    inline System::Void Wind_turbineClass::windturb_dgsyncAsync(
                System::Double pCircuit_V_A_real, 
                System::Double pCircuit_V_A_imag, 
                System::Double pCircuit_V_B_real, 
                System::Double pCircuit_V_B_imag, 
                System::Double pCircuit_V_C_real, 
                System::Double pCircuit_V_C_imag) {
        this->windturb_dgsyncAsync(pCircuit_V_A_real, pCircuit_V_A_imag, pCircuit_V_B_real, pCircuit_V_B_imag, pCircuit_V_C_real, 
            pCircuit_V_C_imag, nullptr);
    }
    
    inline System::Void Wind_turbineClass::windturb_dgsyncAsync(
                System::Double pCircuit_V_A_real, 
                System::Double pCircuit_V_A_imag, 
                System::Double pCircuit_V_B_real, 
                System::Double pCircuit_V_B_imag, 
                System::Double pCircuit_V_C_real, 
                System::Double pCircuit_V_C_imag, 
                System::Object^  userState) {
        if (this->windturb_dgsyncOperationCompleted == nullptr) {
            this->windturb_dgsyncOperationCompleted = gcnew System::Threading::SendOrPostCallback(this, &Wind_TurbineSvc::Wind_turbineClass::Onwindturb_dgsyncOperationCompleted);
        }
        this->InvokeAsync(L"windturb_dgsync", gcnew cli::array< System::Object^  >(6) {pCircuit_V_A_real, pCircuit_V_A_imag, 
                pCircuit_V_B_real, pCircuit_V_B_imag, pCircuit_V_C_real, pCircuit_V_C_imag}, this->windturb_dgsyncOperationCompleted, userState);
    }
    
    inline System::Void Wind_turbineClass::Onwindturb_dgsyncOperationCompleted(System::Object^  arg) {
        {
            System::Web::Services::Protocols::InvokeCompletedEventArgs^  invokeArgs = (cli::safe_cast<System::Web::Services::Protocols::InvokeCompletedEventArgs^  >(arg));
            this->windturb_dgsyncCompleted(this, (gcnew Wind_TurbineSvc::windturb_dgsyncCompletedEventArgs(invokeArgs->Results, 
                    invokeArgs->Error, invokeArgs->Cancelled, invokeArgs->UserState)));
        }
    }
    
    inline System::Int32 Wind_turbineClass::windturb_dg_postsync(System::Int32 t0, System::Int32 t1) {
        cli::array< System::Object^  >^  results = this->Invoke(L"windturb_dg_postsync", gcnew cli::array< System::Object^  >(2) {t0, 
                t1});
        return (*cli::safe_cast<System::Int32^>(results[0]));
    }
    
    inline System::IAsyncResult^  Wind_turbineClass::Beginwindturb_dg_postsync(System::Int32 t0, System::Int32 t1, System::AsyncCallback^  callback, 
                System::Object^  asyncState) {
        return this->BeginInvoke(L"windturb_dg_postsync", gcnew cli::array< System::Object^  >(2) {t0, t1}, callback, asyncState);
    }
    
    inline System::Int32 Wind_turbineClass::Endwindturb_dg_postsync(System::IAsyncResult^  asyncResult) {
        cli::array< System::Object^  >^  results = this->EndInvoke(asyncResult);
        return (*cli::safe_cast<System::Int32^>(results[0]));
    }
    
    inline System::Void Wind_turbineClass::windturb_dg_postsyncAsync(System::Int32 t0, System::Int32 t1) {
        this->windturb_dg_postsyncAsync(t0, t1, nullptr);
    }
    
    inline System::Void Wind_turbineClass::windturb_dg_postsyncAsync(System::Int32 t0, System::Int32 t1, System::Object^  userState) {
        if (this->windturb_dg_postsyncOperationCompleted == nullptr) {
            this->windturb_dg_postsyncOperationCompleted = gcnew System::Threading::SendOrPostCallback(this, &Wind_TurbineSvc::Wind_turbineClass::Onwindturb_dg_postsyncOperationCompleted);
        }
        this->InvokeAsync(L"windturb_dg_postsync", gcnew cli::array< System::Object^  >(2) {t0, t1}, this->windturb_dg_postsyncOperationCompleted, 
            userState);
    }
    
    inline System::Void Wind_turbineClass::Onwindturb_dg_postsyncOperationCompleted(System::Object^  arg) {
        {
            System::Web::Services::Protocols::InvokeCompletedEventArgs^  invokeArgs = (cli::safe_cast<System::Web::Services::Protocols::InvokeCompletedEventArgs^  >(arg));
            this->windturb_dg_postsyncCompleted(this, (gcnew Wind_TurbineSvc::windturb_dg_postsyncCompletedEventArgs(invokeArgs->Results, 
                    invokeArgs->Error, invokeArgs->Cancelled, invokeArgs->UserState)));
        }
    }
    
    inline System::Void Wind_turbineClass::CancelAsync(System::Object^  userState) {
        __super::CancelAsync(userState);
    }
    
    
    inline windturb_dgcreateCompletedEventArgs::windturb_dgcreateCompletedEventArgs(cli::array< System::Object^  >^  results, 
                System::Exception^  exception, System::Boolean cancelled, System::Object^  userState) : 
            System::ComponentModel::AsyncCompletedEventArgs(exception, cancelled, userState) {
        this->results = results;
    }
    
    inline System::Double windturb_dgcreateCompletedEventArgs::Result::get() {
        this->RaiseExceptionIfNecessary();
        return (*cli::safe_cast<System::Double^>(this->results[0]));
    }
    
    
    inline windturb_dginitCompletedEventArgs::windturb_dginitCompletedEventArgs(cli::array< System::Object^  >^  results, 
                System::Exception^  exception, System::Boolean cancelled, System::Object^  userState) : 
            System::ComponentModel::AsyncCompletedEventArgs(exception, cancelled, userState) {
        this->results = results;
    }
    
    inline System::Int32 windturb_dginitCompletedEventArgs::Result::get() {
        this->RaiseExceptionIfNecessary();
        return (*cli::safe_cast<System::Int32^>(this->results[0]));
    }
    
    
    inline windturb_dgsyncCompletedEventArgs::windturb_dgsyncCompletedEventArgs(cli::array< System::Object^  >^  results, 
                System::Exception^  exception, System::Boolean cancelled, System::Object^  userState) : 
            System::ComponentModel::AsyncCompletedEventArgs(exception, cancelled, userState) {
        this->results = results;
    }
    
    inline System::Double windturb_dgsyncCompletedEventArgs::Result::get() {
        this->RaiseExceptionIfNecessary();
        return (*cli::safe_cast<System::Double^>(this->results[0]));
    }
    
    
    inline windturb_dg_postsyncCompletedEventArgs::windturb_dg_postsyncCompletedEventArgs(cli::array< System::Object^  >^  results, 
                System::Exception^  exception, System::Boolean cancelled, System::Object^  userState) : 
            System::ComponentModel::AsyncCompletedEventArgs(exception, cancelled, userState) {
        this->results = results;
    }
    
    inline System::Int32 windturb_dg_postsyncCompletedEventArgs::Result::get() {
        this->RaiseExceptionIfNecessary();
        return (*cli::safe_cast<System::Int32^>(this->results[0]));
    }
}
